name: Deploy docker hub

on:
  push:
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: '20.13.0'
          yarn-version: '1.22.21'
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run lint
        run: yarn lint

      - name: Run lint:css
        run: yarn lint:css

      - name: Run test
        run: yarn test

      - name: Build Storybook
        if: github.ref == 'refs/heads/master'
        run: yarn build-storybook

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./storybook-static
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'

      - name: Clean storybook folder
        if: github.ref == 'refs/heads/master'
        run: rm -rf ./storybook-static